
from tkinter import *
import tkinter
from PyQt5 import QtCore, QtGui, QtWidgets
from sqlalchemy import false


class Ui_Jarvis(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1247, 604)
        
    
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1251, 601))
        self.label.setStyleSheet("background-color: rgb(39, 118, 118);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\Jarvis\Png Files/black.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 60, 641, 391))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\Jarvis\Png Files/jarvis435.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 411, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\Jarvis\Png Files/T8bahf.gif"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 201, 301))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/jarvisstand.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 80, 231, 201))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/zero.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 270, 201, 201))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/circle.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1040, 80, 241, 161))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/jarvis.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(810, 70, 221, 181))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/Iris.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(820, 260, 211, 131))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/loading.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(440, 500, 361, 81))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/wibe.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(430, 410, 381, 91))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/titile.gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(910, 370, 331, 211))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/terminal4.gif"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(0, 480, 261, 151))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/loading.gif"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 390, 201, 131))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/loading4.gif"))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(350, 80, 201, 121))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/J-A-R-V-I-S-thumb.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1050, 250, 171, 121))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("D:\Python\Jarvis\Png Files/wibe.gif"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(720, 0, 256, 51))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n")
        
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(980, 0, 256, 51))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 510, 61, 21))
        self.pushButton.setStyleSheet("background-color: rgb(39, 118, 118);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 510, 61, 21))
        self.pushButton_2.setStyleSheet("background-color: rgb(39, 118, 118);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(800, 510, 64, 18))
        self.pushButton_3.setStyleSheet("background-color: rgb(39, 118, 118);")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
        self.pushButton_3.setText(_translate("MainWindow","Commands"))
        
   

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jarvis = QtWidgets.QMainWindow()
    ui = Ui_Jarvis()
    ui.setupUi(Jarvis)
    
    Jarvis.show()
    sys.exit(app.exec_())
